### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by detxz** [5z3f/lastchaos-classic-emulator#2]
Hello!

Thank you for your job. I really wanted to test this emulator as a flashback, but I've faced the issue as on the screenshot attached. 

![screen](https://user-images.githubusercontent.com/81327843/216595253-80607fac-2b28-434b-b769-d2c83fa07069.jpeg)

The interesting thing is that all this .js files on the right place. I've tested it on VM just in case, same situation. 
Do you have any ideas, maybe?

I also tried to run Nksp.exe, I get this message:
![Снимок экрана 2023-02-03 в 16 15 39](https://user-images.githubusercontent.com/81327843/216601617-b398dd1c-76eb-4a51-bb9b-326493e5897c.png)

Thanks.

**Comment by 5z3f** [comment]
I see that they have changed something with the local paths since the 9.x version of npm, downgrade your node as a workaround for now until I can figure out fix for it.
https://nodejs.org/download/release/v18.12.0/

If you want to run nksp directly, you must start it with the argument "6574".
You can create bat file with this line: `start bin\Nksp 6574`

**Comment by detxz** [comment]
> I see that they have changed something with the local paths since the 9.x version of npm, downgrade your node as a workaround for now until I can figure out fix for it. https://nodejs.org/download/release/v18.12.0/
> 
> If you want to run nksp directly, you must start it with the argument "6574". You can create bat file with this line: `start bin\Nksp 6574`

Oh, thanks a lot, it works fine with 16.14.1 version! 

P.S. I understand that this is not a global project but in concept, is it possible to enable some kind of DB, so someone, for example, could create a new char, give him cash, item, store this data, etc.? Or this project is "locked" so we can use only what it has?

**Comment by 5z3f** [comment]
This is just start of the project. Implementing database would be pointless in current stage so there is just one static character at the moment.
There is not much you can do at the moment, you can check available commands [here](https://github.com/5z3f/lastchaos-classic-emulator/tree/master/GameServer).

**Comment by detxz** [comment]
Yes, sure. Well, I'd like to wish you all the best with this project but for the beginning it's really really cool, to run a game/ server using a few commands. 

Subscribed.

**Comment by 5z3f** [comment]
Looks like it's been fixed in latest node version (18.14.2 LTS / 19.7.0)
